name: autofix.ci

on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

      # Run lint
      - name: 💪 Lint
        run: nr lint -- --fix

      - uses: autofix-ci/action@ea32e3a12414e6d3183163c3424a7d7a8631ad84
